### ISSUE TITLE
Host Port Midi Note out issue (receive error: LIBUSB_ERROR_PIPE) 

### ISSUE THREAD

**Issue by reubenfinger** [zrna-research/akso#17]
Whilst attempting to send clock out usb host port 1 using factory object midi/out/clock and notes out using cpwitz/midi/arpeggiator and a midi/out/note I get a patch load error, and akso restarts. The same exact patches work with axoloti. The error appears below

USB device found
Connected to device.
Firmware version on attached device: 3.0.1.0, crc=0x9922E990
Generate code complete
Compiling patch.
/Users/reubenfinger/Library/Akso/build/xpatch.cpp: In member function ‘void rootc::instanceclock__1::dsp(rootc*, bool, bool, bool&, int32_t&, int32_t&, int)’:
/Users/reubenfinger/Library/Akso/build/xpatch.cpp:120:24: warning: integer overflow in expression of type ‘int’ results in ‘2147483647’ [-Woverflow]
_posfrac &= (1<<31)-1;
~~~~~~~^~
Memory region Used Size Region Size %age Used
SRAM: 3356 B 384 KB 0.85%
SRAM2: 0 GB 8 KB 0.00%
SRAM3: 1768 B 118 KB 1.46%
CCMSRAM: 964 B 116 KB 0.81%
SDRAM: 0 GB 32 MB 0.00%
done /Users/reubenfinger/Library/Akso/build/xpatch
Done compiling patch.
receive error: LIBUSB_ERROR_PIPE
Control transfer failed: -9
Disconnected from device.
java.io.IOException: java.util.concurrent.TimeoutException
java.io.IOException: java.util.concurrent.TimeoutException
at axoloti.connection.USBBulkConnection_v2.read(USBBulkConnection_v2.java:856)
at axoloti.live.patch.PatchViewLive.lambda$goLive$7(PatchViewLive.java:279)
at axoloti.job.JobProcessor.lambda$exec$0(JobProcessor.java:21)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
at axoloti.connection.USBBulkConnection_v2.read(USBBulkConnection_v2.java:852)
… 5 more

**Comment by ivogrig** [comment]
![image](https://user-images.githubusercontent.com/10848442/99155579-76457200-26b9-11eb-96d1-1741854e3b53.png)

[midi_out_crash.zip](https://github.com/zrna-research/akso/files/5541354/midi_out_crash.zip)

Same here, in fact it crashes regardless of which device is selected.
But only if a USB device is connected. 
When using the midi monitor object, I can see incoming messages however.

**Comment by ivogrig** [comment]
I am using such an adapter. I now ordered a direct usb-B to -usb-C adapter, maybe that makes a difference?
![image](https://user-images.githubusercontent.com/10848442/100984034-6eefe680-354a-11eb-88e7-296209bb1d10.png)

Update:
I received my non-adapter cable but the issue persists.
